#!/usr/local/bin/python3.6

var1 = 'Hello, Python'
var2 = 'kai.fantasy'

print('var1 = ', var1)
print('var2 = ', var2)

print('var1[0] ', var1[0])
print('var2[1:5]', var2[1:5])

print('更新 ', var1[:6] + var2)

print('')
print('Python转义字符')

print('\(在行尾时)	续行符')
print('\\	反斜杠符号')
print('\'	单引号')
print('\"	双引号')

print('\a	响铃')
print('\b	退格(Backspace)')
print('\e	转义')
print('\000	空')
print('\n	换行')
print('\v	纵向制表符')
print('\t	横向制表符')
print('\r	回车')
print('\f	换页')
print('\oyy	八进制数，yy代表的字符，例如：\o12代表换行')
print(r'\xyy	十六进制数，yy代表的字符，例如：\x0a代表换行')
print('\other	其它的字符以普通格式输出')
print('')

print('Python字符串格式化')

print('Python 支持格式化字符串的输出 。尽管这样可能会用到非常复杂的表达式，但最基本的用法是将一个值插入到一个有字符串格式符 %s 的字符串中。')


print('这个学生是 %s 他的学号 %d ~' % ('张三', 1003212))

print('python字符串格式化符号')

print('%c	 格式化字符及其ASCII码')
print('%s	 格式化字符串')
print('%d	 格式化整数')
print('%u	 格式化无符号整型')
print('%o	 格式化无符号八进制数')
print('%x	 格式化无符号十六进制数')
print('%X	 格式化无符号十六进制数（大写）')
print('%f	 格式化浮点数字，可指定小数点后的精度')
print('%e	 用科学计数法格式化浮点数')
print('%E	 作用同%e，用科学计数法格式化浮点数')
print('%g	 %f和%e的简写')
print('%G	 %f 和 %E 的简写')
print('%p	 用十六进制数格式化变量的地址')
print('')
print('格式化操作符辅助指令:')

print('*	定义宽度或者小数点精度')
print('-	用做左对齐')
print('+	在正数前面显示加号( + )')
print('<sp>	在正数前面显示空格')
print(r'#	在八进制数前面显示零 0 在十六进制前面显示 0x 或者 0X 取决于用的是 x 还是 X ')
print(r'0	显示的数字前面填充 0 而不是默认的空格')
print(r'%	 % %输出一个单一的 % ')
print('(var)	映射变量(字典参数)')
print('m.n.	m 是显示的最小总宽度,n 是小数点后的位数(如果可用的话)')
print('')


print('三引号让程序员从引号和特殊字符串的泥潭里面解脱出来，自始至终保持一小块字符串的格式是所谓的WYSIWYG（所见即所得）格式的。')
print('')
print('Python 的字符串内建函数')
print('1	capitalize()将字符串的第一个字符转换为大写')
print('2    center(width, fillchar) 返回一个指定的宽度 width 居中的字符串，fillchar 为填充的字符，默认为空格。')
print('3	count(str, beg= 0,end=len(string)) 返回 str 在 string 里面出现的次数，如果 beg 或者 end 指定则返回指定范围内 str 出现的次数')
print('4    bytes.decode(encoding="utf-8", errors="strict") Python3 中没有 decode 方法，但我们可以使用 bytes 对象的 decode() 方法来解码给定的 bytes 对象，这个 bytes 对象可以由 str.encode() 来编码返回。')
print(r'5   encode(encoding="UTF-8",errors="strict") 以 encoding 指定的编码格式编码字符串，如果出错默认报一个ValueError 的异常，除非 errors 指定的是"ignore"或者"replace"')
print('6	endswith(suffix, beg=0, end=len(string)) 检查字符串是否以 obj 结束，如果beg 或者 end 指定则检查指定的范围内是否以 obj 结束，如果是，返回 True,否则返回 False.')
print('7	expandtabs(tabsize=8) 把字符串 string 中的 tab 符号转为空格，tab 符号默认的空格数是 8 。')
print('8	find(str, beg=0 end=len(string)) 检测 str 是否包含在字符串中，如果指定范围 beg 和 end ，则检查是否包含在指定范围内，如果包含返回开始的索引值，否则返回-1')
print('9	index(str, beg=0, end=len(string)) 跟find()方法一样，只不过如果str不在字符串中会报一个异常.')
print('10	isalnum() 如果字符串至少有一个字符并且所有字符都是字母或数字则返 回 True,否则返回 False')
print('11	isalpha() 如果字符串至少有一个字符并且所有字符都是字母则返回 True, 否则返回 False')
print('12	isdigit() 如果字符串只包含数字则返回 True 否则返回 False.')
print('13	islower() 如果字符串中包含至少一个区分大小写的字符，并且所有这些(区分大小写的)字符都是小写，则返回 True，否则返回 False')
print('14	isnumeric() 如果字符串中只包含数字字符，则返回 True，否则返回 False')
print('15	isspace() 如果字符串中只包含空白，则返回 True，否则返回 False.')
print('16	istitle() 如果字符串是标题化的(见 title())则返回 True，否则返回 False')
print('17	isupper() 如果字符串中包含至少一个区分大小写的字符，并且所有这些(区分大小写的)字符都是大写，则返回 True，否则返回 False')
print('18	join(seq) 以指定字符串作为分隔符，将 seq 中所有的元素(的字符串表示)合并为一个新的字符串')
print('19	len(string) 返回字符串长度')
print(
    '20	ljust(width[, fillchar]) 返回一个原字符串左对齐,并使用 fillchar 填充至长度 width 的新字符串，fillchar 默认为空格。')
print('21	lower() 转换字符串中所有大写字符为小写.')
print('22	lstrip() 截掉字符串左边的空格或指定字符。')
print('23	maketrans() 创建字符映射的转换表，对于接受两个参数的最简单的调用方式，第一个参数是字符串，表示需要转换的字符，第二个参数也是字符串表示转换的目标。')
print('24	max(str) 返回字符串 str 中最大的字母。')
print('25	min(str) 返回字符串 str 中最小的字母。')
print(
    '26	replace(old, new [, max]) 把 将字符串中的 str1 替换成 str2,如果 max 指定，则替换不超过 max 次。')
print('27	rfind(str, beg=0,end=len(string)) 类似于 find()函数，不过是从右边开始查找.')
print('28	rindex( str, beg=0, end=len(string)) 类似于 index()，不过是从右边开始.')
print(
    '29	rjust(width,[, fillchar]) 返回一个原字符串右对齐,并使用fillchar(默认空格）填充至长度 width 的新字符串')
print('30	rstrip() 删除字符串字符串末尾的空格.')
print('31	split(str="", num=string.count(str)) num=string.count(str)) 以 str 为分隔符截取字符串，如果 num 有指定值，则仅截取 num 个子字符串')
# 按照行('\r', '\r\n', \n')分隔，返回一个包含各行作为元素的列表，如果参数 keepends 为 False，不包含换行符，如果为 True，则保留换行符。
print('32	splitlines([keepends]) ')
print('33	startswith(str, beg=0,end=len(string)) 检查字符串是否是以 obj 开头，是则返回 True，否则返回 False。如果beg 和 end 指定值，则在指定范围内检查。')
print('34	strip([chars]) 在字符串上执行 lstrip()和 rstrip()')
print('35	swapcase() 将字符串中大写转换为小写，小写转换为大写')
print('36	title() 返回"标题化"的字符串,就是说所有单词都是以大写开始，其余字母均为小写(见 istitle())')
print('37	translate(table, deletechars="") 根据 str 给出的表(包含 256 个字符)转换 string 的字符, 要过滤掉的字符放到 deletechars 参数中')
print('38	upper() 转换字符串中的小写字母为大写')
print('39	zfill (width) 返回长度为 width 的字符串，原字符串右对齐，前面填充0')
print('40	isdecimal() 检查字符串是否只包含十进制字符，如果是返回 true，否则返回 false。')
print('')
print('')
print('')
